Add peer timeout test
svenstaro/wiresmith pull request #11
Opened 2023-04-26 21:12 UTC by tomgroenwoldt

This PR adds an integration test for the peer timeout functionality.

Please merge #24 before this.

2023-05-01 18:00 UTC, tomgroenwoldt commented
Adding another peer resolved the weird behavior.

2023-05-12 10:51 UTC, svenstaro requested changes
Could you make a separate PR for the commit that changes the network setup?

2023-05-14 11:36 UTC, tomgroenwoldt commented on Cargo.toml
> +rand = "0.8.5"
Done.

2023-05-24 15:43 UTC, svenstaro approved these changes

2023-05-24 15:51 UTC, tomgroenwoldt commented on tests/integration.rs
> +    sleep(Duration::from_secs(4)).await;
Oh yeah, this was just for keeping the test running and originally had 2000s. I forgot do delete it.

2023-05-24 15:51 UTC, tomgroenwoldt commented on tests/integration.rs
> +    let (random_peer, remaining_peers) = peers.split_first().expect("Peers are empty.");
Sounds reasonable.

2023-05-24 18:29 UTC, svenstaro approved these changes

2023-05-24 18:30 UTC, merged

2023-05-24 18:30 UTC, svenstaro commented
Great job!